global:
  scrape_interval:     30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.
  external_labels:
    cluster_name: $CLUSTER_NAME

remote_write:
  - url: https://vm.monitoring.gcp.obol.tech/write
    authorization:
      credentials: $PROM_REMOTE_WRITE_TOKEN

scrape_configs:
  - job_name: 'charon-0'
    static_configs:
      - targets: ['node0:3620']
  - job_name: 'charon-1'
    static_configs:
      - targets: ['node1:3620']
  - job_name: 'charon-2'
    static_configs:
      - targets: ['node2:3620']
  - job_name: 'charon-3'
    static_configs:
      - targets: ['node3:3620']
  - job_name: 'vc0'
    static_configs:
      - targets: ['vc0-lighthouse:5064']
  - job_name: 'vc1'
    static_configs:
      - targets: ['vc1-teku:8008']
  - job_name: 'vc2'
    static_configs:
      - targets: ['vc2-teku:8008']
  - job_name: 'vc3'
    static_configs:
      - targets: ['vc3-teku:8008']   
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']