global:
  scrape_interval:     30s # Set the scrape interval to every 12 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 12 seconds. The default is every 1 minute.
  
remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    authorization:
      credentials: 436764:$PROM_REMOTE_WRITE_TOKEN
    name: obol-prom

scrape_configs:
  - job_name: 'charon-0'
    static_configs:
      - targets: ['node0:3620']
  - job_name: 'charon-1'
    static_configs:
      - targets: ['node1:3620']
  - job_name: 'charon-2'
    static_configs:
      - targets: ['node2:3620']
  - job_name: 'charon-3'
    static_configs:
      - targets: ['node3:3620']
  - job_name: 'vc0'
    static_configs:
      - targets: ['vc0-lighthouse:5064']
  - job_name: 'vc1'
    static_configs:
      - targets: ['vc1-teku:8008']
  - job_name: 'vc2'
    static_configs:
      - targets: ['vc2-teku:8008']
  - job_name: 'vc3'
    static_configs:
      - targets: ['vc3-teku:8008']   
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']